#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Power control"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pwr { ptr : * mut u8 } unsafe impl Send for Pwr { } unsafe impl Sync for Pwr { } impl Pwr { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register 1"]
# [inline (always)]
pub const fn cr1 (self) -> crate :: common :: Reg < regs :: Cr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "control register 2"]
# [inline (always)]
pub const fn cr2 (self) -> crate :: common :: Reg < regs :: Cr2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "control register 3"]
# [inline (always)]
pub const fn cr3 (self) -> crate :: common :: Reg < regs :: Cr3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "voltage scaling register"]
# [inline (always)]
pub const fn vosr (self) -> crate :: common :: Reg < regs :: Vosr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "supply voltage monitoring control register"]
# [inline (always)]
pub const fn svmcr (self) -> crate :: common :: Reg < regs :: Svmcr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "wakeup control register 1"]
# [inline (always)]
pub const fn wucr1 (self) -> crate :: common :: Reg < regs :: Wucr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "wakeup control register 2"]
# [inline (always)]
pub const fn wucr2 (self) -> crate :: common :: Reg < regs :: Wucr2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "wakeup control register 3"]
# [inline (always)]
pub const fn wucr3 (self) -> crate :: common :: Reg < regs :: Wucr3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "disable Backup domain register"]
# [inline (always)]
pub const fn dbpcr (self) -> crate :: common :: Reg < regs :: Dbpcr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "security configuration register"]
# [inline (always)]
pub const fn seccfgr (self) -> crate :: common :: Reg < regs :: Seccfgr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "privilege control register"]
# [inline (always)]
pub const fn privcfgr (self) -> crate :: common :: Reg < regs :: Privcfgr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "status register"]
# [inline (always)]
pub const fn sr (self) -> crate :: common :: Reg < regs :: Sr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "supply voltage monitoring status register"]
# [inline (always)]
pub const fn svmsr (self) -> crate :: common :: Reg < regs :: Svmsr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "wakeup status register"]
# [inline (always)]
pub const fn wusr (self) -> crate :: common :: Reg < regs :: Wusr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "wakeup status clear register"]
# [inline (always)]
pub const fn wuscr (self) -> crate :: common :: Reg < regs :: Wuscr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "port Standby IO retention enable register"]
# [inline (always)]
pub const fn ioretenr (self , n : usize) -> crate :: common :: Reg < regs :: Ioretenr , crate :: common :: RW > { assert ! (n < 8usize) ; unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize + n * 8usize) as _) } } # [doc = "port Standby IO retention status register"]
# [inline (always)]
pub const fn ioretra (self , n : usize) -> crate :: common :: Reg < regs :: Ioretr , crate :: common :: RW > { assert ! (n < 8usize) ; unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize + n * 8usize) as _) } } # [doc = "2.4 GHz RADIO status and control register"]
# [inline (always)]
pub const fn radioscr (self) -> crate :: common :: Reg < regs :: Radioscr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0100usize) as _) } } } pub mod regs { # [doc = "control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr1 (pub u32) ; impl Cr1 { # [doc = "Low-power mode selection These bits select the low-power mode entered when the CPU enters the SleepDeep mode. 10x: Standby mode others reserved"]
# [inline (always)]
pub const fn lpms (& self) -> super :: vals :: Lpms { let val = (self . 0 >> 0usize) & 0x07 ; super :: vals :: Lpms :: from_bits (val as u8) } # [doc = "Low-power mode selection These bits select the low-power mode entered when the CPU enters the SleepDeep mode. 10x: Standby mode others reserved"]
# [inline (always)]
pub fn set_lpms (& mut self , val : super :: vals :: Lpms) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val . to_bits () as u32) & 0x07) << 0usize) ; } # [doc = "SRAM2 retention in Standby mode This bit is used to keep the SRAM2 content in Standby retention mode."]
# [inline (always)]
pub const fn r2rsb1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "SRAM2 retention in Standby mode This bit is used to keep the SRAM2 content in Standby retention mode."]
# [inline (always)]
pub fn set_r2rsb1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "BOR0 ultra-low-power mode. This bit is used to reduce the consumption by configuring the BOR0 in discontinuous mode for Stop 1 and Standby modes. Discontinuous mode is only available when BOR levels 1 to 4 and PVD are disabled. Note: This bit must be set to reach the lowest power consumption in the low-power modes. Note: This bit must not be set together with autonomous peripherals using HSI as kernel clock. Note: When BOR level 1 to 4 or PVD is enabled continuous mode applies independent from ULPMEN."]
# [inline (always)]
pub const fn ulpmen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "BOR0 ultra-low-power mode. This bit is used to reduce the consumption by configuring the BOR0 in discontinuous mode for Stop 1 and Standby modes. Discontinuous mode is only available when BOR levels 1 to 4 and PVD are disabled. Note: This bit must be set to reach the lowest power consumption in the low-power modes. Note: This bit must not be set together with autonomous peripherals using HSI as kernel clock. Note: When BOR level 1 to 4 or PVD is enabled continuous mode applies independent from ULPMEN."]
# [inline (always)]
pub fn set_ulpmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "2.4 GHz RADIO SRAMs (RXTXRAM and Sequence RAM) and Sleep clock retention in Standby mode. This bit is used to keep the 2.4 GHz RADIO SRAMs content in Standby retention mode and the 2.4 GHz RADIO sleep timer counter operational."]
# [inline (always)]
pub const fn radiorsb (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "2.4 GHz RADIO SRAMs (RXTXRAM and Sequence RAM) and Sleep clock retention in Standby mode. This bit is used to keep the 2.4 GHz RADIO SRAMs content in Standby retention mode and the 2.4 GHz RADIO sleep timer counter operational."]
# [inline (always)]
pub fn set_radiorsb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "SRAM1 retention in Standby mode This bit is used to keep the SRAM1 content in Standby retention mode."]
# [inline (always)]
pub const fn r1rsb1 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "SRAM1 retention in Standby mode This bit is used to keep the SRAM1 content in Standby retention mode."]
# [inline (always)]
pub fn set_r1rsb1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for Cr1 { # [inline (always)]
fn default () -> Cr1 { Cr1 (0) } } # [doc = "control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr2 (pub u32) ; impl Cr2 { # [doc = "SRAM1 power-down in Stop modes (Stop 0, 1) Note: The SRAM1 retention in Standby mode is controlled by R1RSB1 bit in CR1."]
# [inline (always)]
pub const fn sram1pds1 (& self) -> super :: vals :: Srampds { let val = (self . 0 >> 0usize) & 0x01 ; super :: vals :: Srampds :: from_bits (val as u8) } # [doc = "SRAM1 power-down in Stop modes (Stop 0, 1) Note: The SRAM1 retention in Standby mode is controlled by R1RSB1 bit in CR1."]
# [inline (always)]
pub fn set_sram1pds1 (& mut self , val : super :: vals :: Srampds) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val . to_bits () as u32) & 0x01) << 0usize) ; } # [doc = "SRAM2 power-down in Stop modes (Stop 0, 1) Note: The SRAM2 retention in Standby mode is controlled by R2RSB1 bit in CR1."]
# [inline (always)]
pub const fn sram2pds1 (& self) -> super :: vals :: Srampds { let val = (self . 0 >> 4usize) & 0x01 ; super :: vals :: Srampds :: from_bits (val as u8) } # [doc = "SRAM2 power-down in Stop modes (Stop 0, 1) Note: The SRAM2 retention in Standby mode is controlled by R2RSB1 bit in CR1."]
# [inline (always)]
pub fn set_sram2pds1 (& mut self , val : super :: vals :: Srampds) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val . to_bits () as u32) & 0x01) << 4usize) ; } # [doc = "ICACHE SRAM power-down in Stop modes (Stop 0, 1)"]
# [inline (always)]
pub const fn icrampds (& self) -> super :: vals :: Icrampds { let val = (self . 0 >> 8usize) & 0x01 ; super :: vals :: Icrampds :: from_bits (val as u8) } # [doc = "ICACHE SRAM power-down in Stop modes (Stop 0, 1)"]
# [inline (always)]
pub fn set_icrampds (& mut self , val : super :: vals :: Icrampds) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val . to_bits () as u32) & 0x01) << 8usize) ; } # [doc = "Flash memory fast wakeup from Stop modes (Stop 0, 1) This bit is used to obtain the best trade-off between low-power consumption and wakeup time when exiting the Stop 0 or Stop 1 modes. When this bit is set, the Flash memory remains in normal mode in Stop 0 and Stop 1 modes, which offers a faster startup time with higher consumption."]
# [inline (always)]
pub const fn flashfwu (& self) -> super :: vals :: Flashfwu { let val = (self . 0 >> 14usize) & 0x01 ; super :: vals :: Flashfwu :: from_bits (val as u8) } # [doc = "Flash memory fast wakeup from Stop modes (Stop 0, 1) This bit is used to obtain the best trade-off between low-power consumption and wakeup time when exiting the Stop 0 or Stop 1 modes. When this bit is set, the Flash memory remains in normal mode in Stop 0 and Stop 1 modes, which offers a faster startup time with higher consumption."]
# [inline (always)]
pub fn set_flashfwu (& mut self , val : super :: vals :: Flashfwu) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val . to_bits () as u32) & 0x01) << 14usize) ; } } impl Default for Cr2 { # [inline (always)]
fn default () -> Cr2 { Cr2 (0) } } # [doc = "control register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr3 (pub u32) ; impl Cr3 { # [doc = "Fast soft start"]
# [inline (always)]
pub const fn fsten (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Fast soft start"]
# [inline (always)]
pub fn set_fsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for Cr3 { # [inline (always)]
fn default () -> Cr3 { Cr3 (0) } } # [doc = "disable Backup domain register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dbpcr (pub u32) ; impl Dbpcr { # [doc = "Disable Backup domain write protection In reset state, all registers and SRAM in Backup domain are protected against parasitic write access. This bit must be set to enable the write access to these registers."]
# [inline (always)]
pub const fn dbp (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Disable Backup domain write protection In reset state, all registers and SRAM in Backup domain are protected against parasitic write access. This bit must be set to enable the write access to these registers."]
# [inline (always)]
pub fn set_dbp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for Dbpcr { # [inline (always)]
fn default () -> Dbpcr { Dbpcr (0) } } # [doc = "port A Standby IO retention enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ioretenr (pub u32) ; impl Ioretenr { # [doc = "Port A Standby GPIO retention enable Access can be protected by GPIOA SECy, privilege protection is controlled by SPRIV or NSPRIV. When set, each bit enables the Standby GPIO retention feature for PAy"]
# [inline (always)]
pub const fn en (& self , n : usize) -> bool { assert ! (n < 16usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "Port A Standby GPIO retention enable Access can be protected by GPIOA SECy, privilege protection is controlled by SPRIV or NSPRIV. When set, each bit enables the Standby GPIO retention feature for PAy"]
# [inline (always)]
pub fn set_en (& mut self , n : usize , val : bool) { assert ! (n < 16usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Ioretenr { # [inline (always)]
fn default () -> Ioretenr { Ioretenr (0) } } # [doc = "port A Standby IO retention status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ioretr (pub u32) ; impl Ioretr { # [doc = "Port A Standby GPIO retention active Access can be protected by GPIOA SECy, privilege protection is controlled by SPRIV or NSPRIV."]
# [inline (always)]
pub const fn ret (& self , n : usize) -> bool { assert ! (n < 16usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "Port A Standby GPIO retention active Access can be protected by GPIOA SECy, privilege protection is controlled by SPRIV or NSPRIV."]
# [inline (always)]
pub fn set_ret (& mut self , n : usize , val : bool) { assert ! (n < 16usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Ioretr { # [inline (always)]
fn default () -> Ioretr { Ioretr (0) } } # [doc = "privilege control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Privcfgr (pub u32) ; impl Privcfgr { # [doc = "secure functions privilege configuration This bit is set and reset by software. It can be written only by a secure privileged access."]
# [inline (always)]
pub const fn spriv (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "secure functions privilege configuration This bit is set and reset by software. It can be written only by a secure privileged access."]
# [inline (always)]
pub fn set_spriv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "non-secure functions privilege configuration This bit is set and reset by software. It can be written only by privileged access, secure or non-secure."]
# [inline (always)]
pub const fn nspriv (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "non-secure functions privilege configuration This bit is set and reset by software. It can be written only by privileged access, secure or non-secure."]
# [inline (always)]
pub fn set_nspriv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Privcfgr { # [inline (always)]
fn default () -> Privcfgr { Privcfgr (0) } } # [doc = "2.4 GHz RADIO status and control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Radioscr (pub u32) ; impl Radioscr { # [doc = "2.4 GHz RADIO operating mode. 1x: 2.4 GHz RADIO active mode"]
# [inline (always)]
pub const fn mode (& self) -> super :: vals :: Mode { let val = (self . 0 >> 0usize) & 0x03 ; super :: vals :: Mode :: from_bits (val as u8) } # [doc = "2.4 GHz RADIO operating mode. 1x: 2.4 GHz RADIO active mode"]
# [inline (always)]
pub fn set_mode (& mut self , val : super :: vals :: Mode) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val . to_bits () as u32) & 0x03) << 0usize) ; } # [doc = "2.4 GHz RADIO PHY operating mode"]
# [inline (always)]
pub const fn phymode (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "2.4 GHz RADIO PHY operating mode"]
# [inline (always)]
pub fn set_phymode (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "2.4 GHz RADIO encryption function operating mode"]
# [inline (always)]
pub const fn encmode (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "2.4 GHz RADIO encryption function operating mode"]
# [inline (always)]
pub fn set_encmode (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "2.4 GHz RADIO VDDHPA control word. Bits \\[3:0\\]
see Table 81: PA output power table format for definition. Bit \\[4\\]
rf_event."]
# [inline (always)]
pub const fn rfvddhpa (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [doc = "2.4 GHz RADIO VDDHPA control word. Bits \\[3:0\\]
see Table 81: PA output power table format for definition. Bit \\[4\\]
rf_event."]
# [inline (always)]
pub fn set_rfvddhpa (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } # [doc = "Ready bit for V<sub>DDHPA</sub> voltage level when selecting VDDRFPA input. Note: REGPARDYVDDRFPA does not allow to detect correct V<sub>DDHPA</sub> voltage level when request to lower the level."]
# [inline (always)]
pub const fn regpardyvddrfpa (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Ready bit for V<sub>DDHPA</sub> voltage level when selecting VDDRFPA input. Note: REGPARDYVDDRFPA does not allow to detect correct V<sub>DDHPA</sub> voltage level when request to lower the level."]
# [inline (always)]
pub fn set_regpardyvddrfpa (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Radioscr { # [inline (always)]
fn default () -> Radioscr { Radioscr (0) } } # [doc = "security configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Seccfgr (pub u32) ; impl Seccfgr { # [doc = "WUP1 secure protection"]
# [inline (always)]
pub const fn wup1sec (& self , n : usize) -> bool { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "WUP1 secure protection"]
# [inline (always)]
pub fn set_wup1sec (& mut self , n : usize , val : bool) { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } # [doc = "Low-power modes secure protection"]
# [inline (always)]
pub const fn lpmsec (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Low-power modes secure protection"]
# [inline (always)]
pub fn set_lpmsec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Voltage detection secure protection"]
# [inline (always)]
pub const fn vdmsec (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Voltage detection secure protection"]
# [inline (always)]
pub fn set_vdmsec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Backup domain secure protection"]
# [inline (always)]
pub const fn vbsec (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Backup domain secure protection"]
# [inline (always)]
pub fn set_vbsec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } } impl Default for Seccfgr { # [inline (always)]
fn default () -> Seccfgr { Seccfgr (0) } } # [doc = "status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sr (pub u32) ; impl Sr { # [doc = "Clear Stop and Standby flags Access can be secured by LPMSEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV. Writing 1 to this bit clears the STOPF and SBF flags."]
# [inline (always)]
pub const fn cssf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Clear Stop and Standby flags Access can be secured by LPMSEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV. Writing 1 to this bit clears the STOPF and SBF flags."]
# [inline (always)]
pub fn set_cssf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Stop flag This bit is set by hardware when the device enters a Stop or Standby mode at the same time as the sysclk has been set by hardware to select HSI. It’s cleared by software by writing 1 to the CSSF bit and by hardware when SBF is set."]
# [inline (always)]
pub const fn stopf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Stop flag This bit is set by hardware when the device enters a Stop or Standby mode at the same time as the sysclk has been set by hardware to select HSI. It’s cleared by software by writing 1 to the CSSF bit and by hardware when SBF is set."]
# [inline (always)]
pub fn set_stopf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Standby flag This bit is set by hardware when the device enters the Standby mode and the CPU restart from its reset vector. It’s cleared by writing 1 to the CSSF bit, or by a power-on reset. It is not cleared by the system reset."]
# [inline (always)]
pub const fn sbf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Standby flag This bit is set by hardware when the device enters the Standby mode and the CPU restart from its reset vector. It’s cleared by writing 1 to the CSSF bit, or by a power-on reset. It is not cleared by the system reset."]
# [inline (always)]
pub fn set_sbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for Sr { # [inline (always)]
fn default () -> Sr { Sr (0) } } # [doc = "supply voltage monitoring control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Svmcr (pub u32) ; impl Svmcr { # [doc = "Programmable voltage detector enable"]
# [inline (always)]
pub const fn pvde (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Programmable voltage detector enable"]
# [inline (always)]
pub fn set_pvde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Programmable voltage detector level selection These bits select the voltage threshold detected by the programmable voltage detector:"]
# [inline (always)]
pub const fn pvdls (& self) -> super :: vals :: Pvdls { let val = (self . 0 >> 5usize) & 0x07 ; super :: vals :: Pvdls :: from_bits (val as u8) } # [doc = "Programmable voltage detector level selection These bits select the voltage threshold detected by the programmable voltage detector:"]
# [inline (always)]
pub fn set_pvdls (& mut self , val : super :: vals :: Pvdls) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val . to_bits () as u32) & 0x07) << 5usize) ; } } impl Default for Svmcr { # [inline (always)]
fn default () -> Svmcr { Svmcr (0) } } # [doc = "supply voltage monitoring status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Svmsr (pub u32) ; impl Svmsr { # [doc = "Programmable voltage detector output"]
# [inline (always)]
pub const fn pvdo (& self) -> super :: vals :: Pvdo { let val = (self . 0 >> 4usize) & 0x01 ; super :: vals :: Pvdo :: from_bits (val as u8) } # [doc = "Programmable voltage detector output"]
# [inline (always)]
pub fn set_pvdo (& mut self , val : super :: vals :: Pvdo) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val . to_bits () as u32) & 0x01) << 4usize) ; } # [doc = "Voltage level ready for currently used VOS"]
# [inline (always)]
pub const fn actvosrdy (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Voltage level ready for currently used VOS"]
# [inline (always)]
pub fn set_actvosrdy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "VOS currently applied to V<sub>CORE</sub> This field provides the last VOS value."]
# [inline (always)]
pub const fn actvos (& self) -> super :: vals :: Actvos { let val = (self . 0 >> 16usize) & 0x01 ; super :: vals :: Actvos :: from_bits (val as u8) } # [doc = "VOS currently applied to V<sub>CORE</sub> This field provides the last VOS value."]
# [inline (always)]
pub fn set_actvos (& mut self , val : super :: vals :: Actvos) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val . to_bits () as u32) & 0x01) << 16usize) ; } } impl Default for Svmsr { # [inline (always)]
fn default () -> Svmsr { Svmsr (0) } } # [doc = "voltage scaling register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Vosr (pub u32) ; impl Vosr { # [doc = "Ready bit for V<sub>CORE</sub> voltage scaling output selection Set and cleared by hardware. When decreasing the voltage scaling range, VOSRDY must be one before increasing the SYSCLK frequency."]
# [inline (always)]
pub const fn vosrdy (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Ready bit for V<sub>CORE</sub> voltage scaling output selection Set and cleared by hardware. When decreasing the voltage scaling range, VOSRDY must be one before increasing the SYSCLK frequency."]
# [inline (always)]
pub fn set_vosrdy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Voltage scaling range selection Set a and cleared by software. Cleared by hardware when entering Stop 1 mode. Access can be secured by RCC SYSCLKSEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn vos (& self) -> super :: vals :: Vos { let val = (self . 0 >> 16usize) & 0x01 ; super :: vals :: Vos :: from_bits (val as u8) } # [doc = "Voltage scaling range selection Set a and cleared by software. Cleared by hardware when entering Stop 1 mode. Access can be secured by RCC SYSCLKSEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_vos (& mut self , val : super :: vals :: Vos) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val . to_bits () as u32) & 0x01) << 16usize) ; } } impl Default for Vosr { # [inline (always)]
fn default () -> Vosr { Vosr (0) } } # [doc = "wakeup control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wucr1 (pub u32) ; impl Wucr1 { # [doc = "Wakeup and interrupt pin WKUP1 enable Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wupen (& self , n : usize) -> bool { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "Wakeup and interrupt pin WKUP1 enable Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wupen (& mut self , n : usize , val : bool) { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Wucr1 { # [inline (always)]
fn default () -> Wucr1 { Wucr1 (0) } } # [doc = "wakeup control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wucr2 (pub u32) ; impl Wucr2 { # [doc = "Wakeup pin WKUP1 polarity. This bit must be configured when WUPEN1 = 0. Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wupp (& self , n : usize) -> super :: vals :: Wupp { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; super :: vals :: Wupp :: from_bits (val as u8) } # [doc = "Wakeup pin WKUP1 polarity. This bit must be configured when WUPEN1 = 0. Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wupp (& mut self , n : usize , val : super :: vals :: Wupp) { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val . to_bits () as u32) & 0x01) << offs) ; } } impl Default for Wucr2 { # [inline (always)]
fn default () -> Wucr2 { Wucr2 (0) } } # [doc = "wakeup control register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wucr3 (pub u32) ; impl Wucr3 { # [doc = "Wakeup and interrupt pin WKUP1 selection This field must be configured when WUPEN1 = 0. Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel1 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 0usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP1 selection This field must be configured when WUPEN1 = 0. Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel1 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val . to_bits () as u32) & 0x03) << 0usize) ; } # [doc = "Wakeup and interrupt pin WKUP2 selection This field must be configured when WUPEN2 = 0. Access can be secured by WUP2SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel2 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 2usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP2 selection This field must be configured when WUPEN2 = 0. Access can be secured by WUP2SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel2 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val . to_bits () as u32) & 0x03) << 2usize) ; } # [doc = "Wakeup and interrupt pin WKUP3 selection This field must be configured when WUPEN3 = 0. Access can be secured by WUP3SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel3 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 4usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP3 selection This field must be configured when WUPEN3 = 0. Access can be secured by WUP3SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel3 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val . to_bits () as u32) & 0x03) << 4usize) ; } # [doc = "Wakeup and interrupt pin WKUP4 selection This field must be configured when WUPEN4 = 0. Access can be secured by WUP4SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel4 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 6usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP4 selection This field must be configured when WUPEN4 = 0. Access can be secured by WUP4SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel4 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val . to_bits () as u32) & 0x03) << 6usize) ; } # [doc = "Wakeup and interrupt pin WKUP5 selection This field must be configured when WUPEN5 = 0. Access can be secured by WUP5SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel5 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 8usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP5 selection This field must be configured when WUPEN5 = 0. Access can be secured by WUP5SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel5 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val . to_bits () as u32) & 0x03) << 8usize) ; } # [doc = "Wakeup and interrupt pin WKUP6 selection This field must be configured when WUPEN6 = 0. Access can be secured by WUP6SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel6 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 10usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP6 selection This field must be configured when WUPEN6 = 0. Access can be secured by WUP6SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel6 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val . to_bits () as u32) & 0x03) << 10usize) ; } # [doc = "Wakeup and interrupt pin WKUP7 selection This field must be configured when WUPEN7 = 0. Access can be secured by WUP7SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel7 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 12usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP7 selection This field must be configured when WUPEN7 = 0. Access can be secured by WUP7SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel7 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val . to_bits () as u32) & 0x03) << 12usize) ; } # [doc = "Wakeup and interrupt pin WKUP8 selection This field must be configured when WUPEN8 = 0. Access can be secured by WUP8SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub const fn wusel8 (& self) -> super :: vals :: Wusel { let val = (self . 0 >> 14usize) & 0x03 ; super :: vals :: Wusel :: from_bits (val as u8) } # [doc = "Wakeup and interrupt pin WKUP8 selection This field must be configured when WUPEN8 = 0. Access can be secured by WUP8SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV."]
# [inline (always)]
pub fn set_wusel8 (& mut self , val : super :: vals :: Wusel) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val . to_bits () as u32) & 0x03) << 14usize) ; } } impl Default for Wucr3 { # [inline (always)]
fn default () -> Wucr3 { Wucr3 (0) } } # [doc = "wakeup status clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wuscr (pub u32) ; impl Wuscr { # [doc = "Clear wakeup flag 1 Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV. Writing 1 to this bit clears the WUF1 flag in WUSR."]
# [inline (always)]
pub const fn cwuf (& self , n : usize) -> bool { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "Clear wakeup flag 1 Access can be secured by WUP1SEC. When secure, a non-secure read/write access is RAZ/WI. It does not generate an illegal access interrupt. This bit can be protected against unprivileged access when secure with SPRIV or when non-secure with NSPRIV. Writing 1 to this bit clears the WUF1 flag in WUSR."]
# [inline (always)]
pub fn set_cwuf (& mut self , n : usize , val : bool) { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Wuscr { # [inline (always)]
fn default () -> Wuscr { Wuscr (0) } } # [doc = "wakeup status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wusr (pub u32) ; impl Wusr { # [doc = "Wakeup and interrupt pending flag 1 This bit is set when a wakeup event is detected on WKUP1 pin. This bit is cleared by writing 1 in the CWUF1 bit of WUSCR or by hardware when WUPEN1 = 0."]
# [inline (always)]
pub const fn wuf (& self , n : usize) -> bool { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "Wakeup and interrupt pending flag 1 This bit is set when a wakeup event is detected on WKUP1 pin. This bit is cleared by writing 1 in the CWUF1 bit of WUSCR or by hardware when WUPEN1 = 0."]
# [inline (always)]
pub fn set_wuf (& mut self , n : usize , val : bool) { assert ! (n < 8usize) ; let offs = 0usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Wusr { # [inline (always)]
fn default () -> Wusr { Wusr (0) } } } pub mod vals { # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Actvos { # [doc = "Range 2 (lowest power)"]
RANGE2 = 0x0 , # [doc = "Range 1 (highest frequency)"]
RANGE1 = 0x01 , } impl Actvos { # [inline (always)]
pub const fn from_bits (val : u8) -> Actvos { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Actvos { # [inline (always)]
fn from (val : u8) -> Actvos { Actvos :: from_bits (val) } } impl From < Actvos > for u8 { # [inline (always)]
fn from (val : Actvos) -> u8 { Actvos :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Flashfwu { # [doc = "Flash memory enters low-power mode in Stop 0 and Stop 1 modes (lower-power consumption)."]
LOWPOWER = 0x0 , # [doc = "Flash memory remains in normal mode in Stop 0 and Stop 1 modes (faster wakeup time)."]
NORMAL = 0x01 , } impl Flashfwu { # [inline (always)]
pub const fn from_bits (val : u8) -> Flashfwu { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Flashfwu { # [inline (always)]
fn from (val : u8) -> Flashfwu { Flashfwu :: from_bits (val) } } impl From < Flashfwu > for u8 { # [inline (always)]
fn from (val : Flashfwu) -> u8 { Flashfwu :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Icrampds { # [doc = "ICACHE SRAM content retained in Stop modes"]
RETAINED = 0x0 , # [doc = "ICACHE SRAM content lost in Stop modes"]
NOTRETAINED = 0x01 , } impl Icrampds { # [inline (always)]
pub const fn from_bits (val : u8) -> Icrampds { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Icrampds { # [inline (always)]
fn from (val : u8) -> Icrampds { Icrampds :: from_bits (val) } } impl From < Icrampds > for u8 { # [inline (always)]
fn from (val : Icrampds) -> u8 { Icrampds :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Lpms { # [doc = "Stop 0 mode"]
STOP0 = 0x0 , # [doc = "Stop 1 mode"]
STOP1 = 0x01 , _RESERVED_2 = 0x02 , _RESERVED_3 = 0x03 , _RESERVED_4 = 0x04 , _RESERVED_5 = 0x05 , _RESERVED_6 = 0x06 , _RESERVED_7 = 0x07 , } impl Lpms { # [inline (always)]
pub const fn from_bits (val : u8) -> Lpms { unsafe { core :: mem :: transmute (val & 0x07) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Lpms { # [inline (always)]
fn from (val : u8) -> Lpms { Lpms :: from_bits (val) } } impl From < Lpms > for u8 { # [inline (always)]
fn from (val : Lpms) -> u8 { Lpms :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Mode { # [doc = "2.4 GHz RADIO deep sleep mode"]
DEEPSLEEP = 0x0 , # [doc = "2.4 GHz RADIO sleep mode"]
SLEEP = 0x01 , _RESERVED_2 = 0x02 , _RESERVED_3 = 0x03 , } impl Mode { # [inline (always)]
pub const fn from_bits (val : u8) -> Mode { unsafe { core :: mem :: transmute (val & 0x03) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Mode { # [inline (always)]
fn from (val : u8) -> Mode { Mode :: from_bits (val) } } impl From < Mode > for u8 { # [inline (always)]
fn from (val : Mode) -> u8 { Mode :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Pvdls { # [doc = "VPVD0 around 2.0 V"]
V20 = 0x0 , # [doc = "VPVD1 around 2.2 V"]
V22 = 0x01 , # [doc = "VPVD2 around 2.4 V"]
V24 = 0x02 , # [doc = "VPVD3 around 2.5 V"]
V25 = 0x03 , # [doc = "VPVD4 around 2.6 V"]
V26 = 0x04 , # [doc = "VPVD5 around 2.8 V"]
V28 = 0x05 , # [doc = "VPVD6 around 2.9 V"]
V29 = 0x06 , # [doc = "External input analog voltage PVD_IN (compared internally to VREFINT)"]
PVD_IN = 0x07 , } impl Pvdls { # [inline (always)]
pub const fn from_bits (val : u8) -> Pvdls { unsafe { core :: mem :: transmute (val & 0x07) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Pvdls { # [inline (always)]
fn from (val : u8) -> Pvdls { Pvdls :: from_bits (val) } } impl From < Pvdls > for u8 { # [inline (always)]
fn from (val : Pvdls) -> u8 { Pvdls :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Pvdo { # [doc = "VDD is equal or above the PVD threshold selected by PVDLS\\[2:0\\]."]
ABOVEOREQUAL = 0x0 , # [doc = "VDD is below the PVD threshold selected by PVDLS\\[2:0\\]."]
BELOW = 0x01 , } impl Pvdo { # [inline (always)]
pub const fn from_bits (val : u8) -> Pvdo { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Pvdo { # [inline (always)]
fn from (val : u8) -> Pvdo { Pvdo :: from_bits (val) } } impl From < Pvdo > for u8 { # [inline (always)]
fn from (val : Pvdo) -> u8 { Pvdo :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Srampds { # [doc = "SRAM1 content retained in Stop modes"]
POWEREDON = 0x0 , # [doc = "SRAM1 content lost in Stop modes"]
POWEREDOFF = 0x01 , } impl Srampds { # [inline (always)]
pub const fn from_bits (val : u8) -> Srampds { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Srampds { # [inline (always)]
fn from (val : u8) -> Srampds { Srampds :: from_bits (val) } } impl From < Srampds > for u8 { # [inline (always)]
fn from (val : Srampds) -> u8 { Srampds :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Vos { # [doc = "Range 2 (lowest power)"]
RANGE2 = 0x0 , # [doc = "Range 1 (highest frequency)."]
RANGE1 = 0x01 , } impl Vos { # [inline (always)]
pub const fn from_bits (val : u8) -> Vos { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Vos { # [inline (always)]
fn from (val : u8) -> Vos { Vos :: from_bits (val) } } impl From < Vos > for u8 { # [inline (always)]
fn from (val : Vos) -> u8 { Vos :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Wupp { # [doc = "Detection on high level (rising edge)"]
HIGH = 0x0 , # [doc = "Detection on low level (falling edge)"]
LOW = 0x01 , } impl Wupp { # [inline (always)]
pub const fn from_bits (val : u8) -> Wupp { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Wupp { # [inline (always)]
fn from (val : u8) -> Wupp { Wupp :: from_bits (val) } } impl From < Wupp > for u8 { # [inline (always)]
fn from (val : Wupp) -> u8 { Wupp :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Wusel { # [doc = "reserved"]
B_0X0 = 0x0 , # [doc = "WKUP3_1"]
B_0X1 = 0x01 , # [doc = "WKUP3_2"]
B_0X2 = 0x02 , # [doc = "reserved"]
B_0X3 = 0x03 , } impl Wusel { # [inline (always)]
pub const fn from_bits (val : u8) -> Wusel { unsafe { core :: mem :: transmute (val & 0x03) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Wusel { # [inline (always)]
fn from (val : u8) -> Wusel { Wusel :: from_bits (val) } } impl From < Wusel > for u8 { # [inline (always)]
fn from (val : Wusel) -> u8 { Wusel :: to_bits (val) } } }