
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[
        Block {
            name: "Comp",
            extends: None,
            description: Some("Comparator with one channel."),
            items: &[
                BlockItem {
                    name: "sr",
                    description: Some("Comparator status register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::Read,
                        bit_size: 32,
                        fieldset: Some("SrSingle"),
                    }),
                },
                BlockItem {
                    name: "icfr",
                    description: Some("Comparator interrupt clear flag register."),
                    array: None,
                    byte_offset: 0x4,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("IcfrSingle"),
                    }),
                },
                BlockItem {
                    name: "cfgr",
                    description: Some("Comparator configuration register."),
                    array: None,
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("CfgrSingle"),
                    }),
                },
            ],
        },
        Block {
            name: "CompChannel",
            extends: None,
            description: Some("Comparator channel."),
            items: &[BlockItem {
                name: "cfgr",
                description: Some("Comparator configuration register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("CfgrDual"),
                }),
            }],
        },
        Block {
            name: "CompCommon",
            extends: None,
            description: Some("Common register block for a pair of comparators."),
            items: &[
                BlockItem {
                    name: "sr",
                    description: Some("Comparator status register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::Read,
                        bit_size: 32,
                        fieldset: Some("SrDual"),
                    }),
                },
                BlockItem {
                    name: "icfr",
                    description: Some("Comparator interrupt clear flag register."),
                    array: None,
                    byte_offset: 0x4,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("IcfrDual"),
                    }),
                },
                BlockItem {
                    name: "cfgr",
                    description: Some("Comparator configuration register."),
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 4 })),
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("CfgrDual"),
                    }),
                },
            ],
        },
    ],
    fieldsets: &[
        FieldSet {
            name: "CfgrDual",
            extends: None,
            description: Some("Comparator configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Comparator channel enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "brgen",
                    description: Some("Scaler bridge enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "scalen",
                    description: Some("Voltage scaler enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "polarity",
                    description: Some("Comparator channel polarity selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "winmode",
                    description: Some("Comparator non-inverting input selector for window mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iten",
                    description: Some("Comparator channel interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hyst",
                    description: Some("Comparator channel hysteresis selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Hyst"),
                },
                Field {
                    name: "pwrmode",
                    description: Some("Power mode of the comparator channel."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Pwrmode"),
                },
                Field {
                    name: "winout",
                    description: Some("Comparator output selector for window mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inmsel",
                    description: Some("Comparator channel inverting input selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inpsel",
                    description: Some("Comparator channel non-inverting input selection."),
                    bit_offset: BitOffset::Cursed(CursedBitOffset {
                        ranges: &[20..=20, 22..=22],
                    }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "blanking",
                    description: Some("Comparator channel blanking source selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lock",
                    description: Some("Comparator configuration register lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "CfgrSingle",
            extends: None,
            description: Some("Comparator configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Comparator channel enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "brgen",
                    description: Some("Scaler bridge enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "scalen",
                    description: Some("Voltage scaler enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "polarity",
                    description: Some("Comparator channel polarity selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iten",
                    description: Some("Comparator channel interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hyst",
                    description: Some("Comparator channel hysteresis selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Hyst"),
                },
                Field {
                    name: "pwrmode",
                    description: Some("Power mode of the comparator channel."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Pwrmode"),
                },
                Field {
                    name: "inmsel",
                    description: Some("Comparator channel inverting input selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inpsel",
                    description: Some("Comparator channel non-inverting input selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "blanking",
                    description: Some("Comparator channel blanking source selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lock",
                    description: Some("Comparator configuration register lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "IcfrDual",
            extends: None,
            description: Some("Comparator interrupt clear flag register."),
            bit_size: 32,
            fields: &[Field {
                name: "ccif",
                description: Some("Clear comparator channel interrupt flag."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 2, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "IcfrSingle",
            extends: None,
            description: Some("Comparator interrupt clear flag register."),
            bit_size: 32,
            fields: &[Field {
                name: "ccif",
                description: Some("Clear comparator channel interrupt flag."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "SrDual",
            extends: None,
            description: Some("Comparator status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "cval",
                    description: Some("Comparator channel output status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 1 })),
                    enumm: None,
                },
                Field {
                    name: "cif",
                    description: Some("Comparator channel interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 1 })),
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "SrSingle",
            extends: None,
            description: Some("Comparator status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "cval",
                    description: Some("Comparator channel output status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cif",
                    description: Some("Comparator channel interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Hyst",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "High",
                    description: None,
                    value: 3,
                },
                EnumVariant {
                    name: "Low",
                    description: None,
                    value: 1,
                },
                EnumVariant {
                    name: "Medium",
                    description: None,
                    value: 2,
                },
                EnumVariant {
                    name: "None",
                    description: None,
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Pwrmode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "HighSpeed",
                    description: Some("High speed and high power."),
                    value: 0,
                },
                EnumVariant {
                    name: "MediumSpeed",
                    description: Some("Medium speed and medium power."),
                    value: 1,
                },
            ],
        },
    ],
};
