
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Dbgmcu",
        extends: None,
        description: Some("DBGMCU address block description."),
        items: &[
            BlockItem {
                name: "dbgmcu_idcode",
                description: Some("DBGMCU identity code register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuIdcode"),
                }),
            },
            BlockItem {
                name: "dbgmcu_cr",
                description: Some("DBGMCU configuration register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuCr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_apb1lfzr",
                description: Some("DBGMCU APB1L peripheral freeze register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuApb1lfzr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_apb2fzr",
                description: Some("DBGMCU APB2 peripheral freeze register."),
                array: None,
                byte_offset: 0x10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuApb2fzr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_apb3fzr",
                description: Some("DBGMCU APB3 peripheral freeze register."),
                array: None,
                byte_offset: 0x14,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuApb3fzr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_ahb1fzr",
                description: Some("DBGMCU AHB1 peripheral freeze register."),
                array: None,
                byte_offset: 0x20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuAhb1fzr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_sr",
                description: Some("DBGMCU status register."),
                array: None,
                byte_offset: 0xfc,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("DbgmcuSr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_dbg_auth_host",
                description: Some("DBGMCU debug authentication mailbox host register."),
                array: None,
                byte_offset: 0x100,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuDbgAuthHost"),
                }),
            },
            BlockItem {
                name: "dbgmcu_dbg_auth_device",
                description: Some("DBGMCU debug authentication mailbox device register."),
                array: None,
                byte_offset: 0x104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuDbgAuthDevice"),
                }),
            },
            BlockItem {
                name: "dbgmcu_dbg_bskey_pwd",
                description: Some("DBGMCU boundary-scan key password register."),
                array: None,
                byte_offset: 0x10c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("DbgmcuDbgBskeyPwd"),
                }),
            },
            BlockItem {
                name: "dbgmcu_dbg_valr",
                description: Some("DBGMCU debug OEMKEY validation register."),
                array: None,
                byte_offset: 0x110,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuDbgValr"),
                }),
            },
            BlockItem {
                name: "dbgmcu_pidr4",
                description: Some("DBGMCU CoreSight peripheral identity register 4."),
                array: None,
                byte_offset: 0xfd0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuPidr4"),
                }),
            },
            BlockItem {
                name: "dbgmcu_pidr0",
                description: Some("DBGMCU CoreSight peripheral identity register 0."),
                array: None,
                byte_offset: 0xfe0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuPidr0"),
                }),
            },
            BlockItem {
                name: "dbgmcu_pidr1",
                description: Some("DBGMCU CoreSight peripheral identity register 1."),
                array: None,
                byte_offset: 0xfe4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuPidr1"),
                }),
            },
            BlockItem {
                name: "dbgmcu_pidr2",
                description: Some("DBGMCU CoreSight peripheral identity register 2."),
                array: None,
                byte_offset: 0xfe8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuPidr2"),
                }),
            },
            BlockItem {
                name: "dbgmcu_pidr3",
                description: Some("DBGMCU CoreSight peripheral identity register 3."),
                array: None,
                byte_offset: 0xfec,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuPidr3"),
                }),
            },
            BlockItem {
                name: "dbgmcu_cidr0",
                description: Some("DBGMCU CoreSight component identity register 0."),
                array: None,
                byte_offset: 0xff0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuCidr0"),
                }),
            },
            BlockItem {
                name: "dbgmcu_cidr1",
                description: Some("DBGMCU CoreSight component identity register 1."),
                array: None,
                byte_offset: 0xff4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuCidr1"),
                }),
            },
            BlockItem {
                name: "dbgmcu_cidr2",
                description: Some("DBGMCU CoreSight component identity register 2."),
                array: None,
                byte_offset: 0xff8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuCidr2"),
                }),
            },
            BlockItem {
                name: "dbgmcu_cidr3",
                description: Some("DBGMCU CoreSight component identity register 3."),
                array: None,
                byte_offset: 0xffc,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("DbgmcuCidr3"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "DbgmcuAhb1fzr",
            extends: None,
            description: Some("DBGMCU AHB1 peripheral freeze register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "lpdma1_0_stop",
                    description: Some("LPDMA1 channel 0 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_1_stop",
                    description: Some("LPDMA1 channel 1 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_2_stop",
                    description: Some("LPDMA1 channel 2 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_3_stop",
                    description: Some("LPDMA1 channel 3 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_4_stop",
                    description: Some("LPDMA1 channel 4 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_5_stop",
                    description: Some("LPDMA1 channel 5 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_6_stop",
                    description: Some("LPDMA1 channel 6 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma1_7_stop",
                    description: Some("LPDMA1 channel 7 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_0_stop",
                    description: Some("LPDMA2 channel 0 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_1_stop",
                    description: Some("LPDMA2 channel 1 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_2_stop",
                    description: Some("LPDMA2 channel 2 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_3_stop",
                    description: Some("LPDMA2 channel 3 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_4_stop",
                    description: Some("LPDMA2 channel 4 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_5_stop",
                    description: Some("LPDMA2 channel 5 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_6_stop",
                    description: Some("LPDMA2 channel 6 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lpdma2_7_stop",
                    description: Some("LPDMA2 channel 7stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuApb1lfzr",
            extends: None,
            description: Some("DBGMCU APB1L peripheral freeze register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tim2_stop",
                    description: Some("TIM2 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim3_stop",
                    description: Some("TIM3 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim4_stop",
                    description: Some("TIM4 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim5_stop",
                    description: Some("TIM5 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim6_stop",
                    description: Some("TIM6 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim7_stop",
                    description: Some("TIM7 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim12_stop",
                    description: Some("TIM12 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wwdg_stop",
                    description: Some("WWDG stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iwdg_stop",
                    description: Some("IWDG stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c1_stop",
                    description: Some("I2C1 SMBUS timeout stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c2_stop",
                    description: Some("I2C2 SMBUS timeout stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i3c1_stop",
                    description: Some("I3C1 SCL stall counter stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuApb2fzr",
            extends: None,
            description: Some("DBGMCU APB2 peripheral freeze register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tim1_stop",
                    description: Some("TIM1 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim8_stop",
                    description: Some("TIM8 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim15_stop",
                    description: Some("TIM15 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim16_stop",
                    description: Some("TIM16 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tim17_stop",
                    description: Some("TIM17 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuApb3fzr",
            extends: None,
            description: Some("DBGMCU APB3 peripheral freeze register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "lptim1_stop",
                    description: Some("LPTIM1 stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rtc_stop",
                    description: Some("RTC stop in debug."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuCidr0",
            extends: None,
            description: Some("DBGMCU CoreSight component identity register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "preamble",
                description: Some("Component identification bits [7:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuCidr1",
            extends: None,
            description: Some("DBGMCU CoreSight component identity register 1."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "preamble",
                    description: Some("Component identification bits [11:8]."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "class",
                    description: Some("Component identification bits [15:12] - component class."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuCidr2",
            extends: None,
            description: Some("DBGMCU CoreSight component identity register 2."),
            bit_size: 32,
            fields: &[Field {
                name: "preamble",
                description: Some("Component identification bits [23:16]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuCidr3",
            extends: None,
            description: Some("DBGMCU CoreSight component identity register 3."),
            bit_size: 32,
            fields: &[Field {
                name: "preamble",
                description: Some("Component identification bits [31:24]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuCr",
            extends: None,
            description: Some("DBGMCU configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sleep",
                    description: Some("Debug in Sleep mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stop",
                    description: Some("Debug in Stop mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "standby",
                    description: Some("Debug in Standby mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "trace_ioen",
                    description: Some("Trace pin enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "trace_en",
                    description: Some("Trace port and clock enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "trace_mode",
                    description: Some("Trace pin assignment."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("TraceMode"),
                },
            ],
        },
        FieldSet {
            name: "DbgmcuDbgAuthDevice",
            extends: None,
            description: Some("DBGMCU debug authentication mailbox device register."),
            bit_size: 32,
            fields: &[Field {
                name: "auth_id",
                description: Some("Device specific ID used for RDP regression."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuDbgAuthHost",
            extends: None,
            description: Some("DBGMCU debug authentication mailbox host register."),
            bit_size: 32,
            fields: &[Field {
                name: "auth_key",
                description: Some("Device authentication key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuDbgBskeyPwd",
            extends: None,
            description: Some("DBGMCU boundary-scan key password register."),
            bit_size: 32,
            fields: &[Field {
                name: "bskey_pwd",
                description: Some("Boundary-scan key (BS key)."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuDbgValr",
            extends: None,
            description: Some("DBGMCU debug OEMKEY validation register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "val_rdy",
                    description: Some("Validation ready."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "val_oemkey",
                    description: Some("OEMKEY validation."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuIdcode",
            extends: None,
            description: Some("DBGMCU identity code register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dev_id",
                    description: Some("Device identification."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 12,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rev_id",
                    description: Some("Revision of the device."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuPidr0",
            extends: None,
            description: Some("DBGMCU CoreSight peripheral identity register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "partnum",
                description: Some("Part number bits [7:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "DbgmcuPidr1",
            extends: None,
            description: Some("DBGMCU CoreSight peripheral identity register 1."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "partnum",
                    description: Some("Part number bits [11:8]."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "jep106id",
                    description: Some("JEP106 identity code bits [3:0]."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuPidr2",
            extends: None,
            description: Some("DBGMCU CoreSight peripheral identity register 2."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "jep106id",
                    description: Some("JEP106 identity code bits [6:4]."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "jedec",
                    description: Some("JEDEC assigned value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "revision",
                    description: Some("Component revision number."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuPidr3",
            extends: None,
            description: Some("DBGMCU CoreSight peripheral identity register 3."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "cmod",
                    description: Some("Customer modified."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "revand",
                    description: Some("Metal fix version."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "DbgmcuPidr4",
            extends: None,
            description: Some("DBGMCU CoreSight peripheral identity register 4."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "jep106con",
                    description: Some("JEP106 continuation code."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "size",
                    description: Some("Register file size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Size"),
                },
            ],
        },
        FieldSet {
            name: "DbgmcuSr",
            extends: None,
            description: Some("DBGMCU status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ap_present",
                    description: Some("Access port present."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ap_enabled",
                    description: Some("Access port enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Size",
            description: None,
            bit_size: 4,
            variants: &[EnumVariant {
                name: "B0x0",
                description: Some("The register file occupies a single 4-Kbyte region."),
                value: 0,
            }],
        },
        Enum {
            name: "TraceMode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "B0x0",
                    description: Some("Trace pins assigned for asynchronous mode (TRACESWO)."),
                    value: 0,
                },
                EnumVariant {
                    name: "B0x1",
                    description: Some(
                        "Trace pins assigned for synchronous mode with a port width of 1 (TRACECK, TRACED0).",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "B0x2",
                    description: Some(
                        "Trace pins assigned for synchronous mode with a port width of 2 ((TRACECK, TRACED0-1).",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "B0x3",
                    description: Some(
                        "Trace pins assigned for synchronous mode with a port width of 4 ((TRACECK, TRACED0-3).",
                    ),
                    value: 3,
                },
            ],
        },
    ],
};
