
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Exti",
        extends: None,
        description: Some("EXTI address block description."),
        items: &[
            BlockItem {
                name: "rtsr1",
                description: Some("EXTI rising trigger selection register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rtsr1"),
                }),
            },
            BlockItem {
                name: "ftsr1",
                description: Some("EXTI falling trigger selection register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ftsr1"),
                }),
            },
            BlockItem {
                name: "swier1",
                description: Some("EXTI software interrupt event register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swier1"),
                }),
            },
            BlockItem {
                name: "rpr1",
                description: Some("EXTI rising edge pending register."),
                array: None,
                byte_offset: 0xc,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rpr1"),
                }),
            },
            BlockItem {
                name: "fpr1",
                description: Some("EXTI falling edge pending register."),
                array: None,
                byte_offset: 0x10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fpr1"),
                }),
            },
            BlockItem {
                name: "seccfgr1",
                description: Some("EXTI security configuration register."),
                array: None,
                byte_offset: 0x14,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Seccfgr1"),
                }),
            },
            BlockItem {
                name: "privcfgr1",
                description: Some("EXTI privilege configuration register."),
                array: None,
                byte_offset: 0x18,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Privcfgr1"),
                }),
            },
            BlockItem {
                name: "exticr1",
                description: Some("EXTI external interrupt selection register."),
                array: None,
                byte_offset: 0x60,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Exticr1"),
                }),
            },
            BlockItem {
                name: "exticr2",
                description: Some("EXTI external interrupt selection register."),
                array: None,
                byte_offset: 0x64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Exticr2"),
                }),
            },
            BlockItem {
                name: "exticr3",
                description: Some("EXTI external interrupt selection register."),
                array: None,
                byte_offset: 0x68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Exticr3"),
                }),
            },
            BlockItem {
                name: "exticr4",
                description: Some("EXTI external interrupt selection register."),
                array: None,
                byte_offset: 0x6c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Exticr4"),
                }),
            },
            BlockItem {
                name: "lockr",
                description: Some("EXTI lock register."),
                array: None,
                byte_offset: 0x70,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Lockr"),
                }),
            },
            BlockItem {
                name: "imr1",
                description: Some("EXTI CPU wake-up with interrupt mask register."),
                array: None,
                byte_offset: 0x80,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Imr1"),
                }),
            },
            BlockItem {
                name: "emr1",
                description: Some("EXTI CPU wake-up with event mask register."),
                array: None,
                byte_offset: 0x84,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Emr1"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Emr1",
            extends: None,
            description: Some("EXTI CPU wake-up with event mask register."),
            bit_size: 32,
            fields: &[Field {
                name: "em",
                description: Some("CPU wake-up with event generation mask on event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Exticr1",
            extends: None,
            description: Some("EXTI external interrupt selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "exti",
                description: Some("None."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Exticr2",
            extends: None,
            description: Some("EXTI external interrupt selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "exti",
                description: Some("None."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Exticr3",
            extends: None,
            description: Some("EXTI external interrupt selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "exti",
                description: Some("None."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Exticr4",
            extends: None,
            description: Some("EXTI external interrupt selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "exti",
                description: Some("None."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fpr1",
            extends: None,
            description: Some("EXTI falling edge pending register."),
            bit_size: 32,
            fields: &[Field {
                name: "fpif",
                description: Some("configurable event inputs i falling edge pending bit."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ftsr1",
            extends: None,
            description: Some("EXTI falling trigger selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "ft",
                description: Some("Falling trigger event configuration bit of configurable event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Imr1",
            extends: None,
            description: Some("EXTI CPU wake-up with interrupt mask register."),
            bit_size: 32,
            fields: &[Field {
                name: "im",
                description: Some("CPU wake-up with interrupt mask on event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lockr",
            extends: None,
            description: Some("EXTI lock register."),
            bit_size: 32,
            fields: &[Field {
                name: "lock",
                description: Some("Global security and privilege configuration registers (SECCFGR and PRIVCFGR) lock."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Privcfgr1",
            extends: None,
            description: Some("EXTI privilege configuration register."),
            bit_size: 32,
            fields: &[Field {
                name: "priv_",
                description: Some("Security enable on event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rpr1",
            extends: None,
            description: Some("EXTI rising edge pending register."),
            bit_size: 32,
            fields: &[Field {
                name: "rpif",
                description: Some("Configurable event input i rising edge pending bit."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rtsr1",
            extends: None,
            description: Some("EXTI rising trigger selection register."),
            bit_size: 32,
            fields: &[Field {
                name: "rt",
                description: Some("Rising trigger event configuration bit of configurable event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Seccfgr1",
            extends: None,
            description: Some("EXTI security configuration register."),
            bit_size: 32,
            fields: &[Field {
                name: "sec",
                description: Some("Security enable on event input i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Swier1",
            extends: None,
            description: Some("EXTI software interrupt event register."),
            bit_size: 32,
            fields: &[Field {
                name: "swi",
                description: Some("Software interrupt on event i."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 23, stride: 1 })),
                enumm: None,
            }],
        },
    ],
    enums: &[],
};
