
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Gfxmmu",
        extends: None,
        description: Some("Chrom-GRC."),
        items: &[
            BlockItem {
                name: "cr",
                description: Some("GFXMMU configuration register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cr"),
                }),
            },
            BlockItem {
                name: "sr",
                description: Some("GFXMMU status register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Sr"),
                }),
            },
            BlockItem {
                name: "fcr",
                description: Some("GFXMMU flag clear register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fcr"),
                }),
            },
            BlockItem {
                name: "dvr",
                description: Some("GFXMMU default value register."),
                array: None,
                byte_offset: 0x10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dvr"),
                }),
            },
            BlockItem {
                name: "dar",
                description: Some("GFXMMU default alpha register."),
                array: None,
                byte_offset: 0x14,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dar"),
                }),
            },
            BlockItem {
                name: "bcr",
                description: Some("GFXMMU buffer 0 configuration register."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 4 })),
                byte_offset: 0x20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bcr"),
                }),
            },
            BlockItem {
                name: "lutl",
                description: Some("GFXMMU LUT entry 0 low."),
                array: Some(Array::Regular(RegularArray { len: 1024, stride: 8 })),
                byte_offset: 0x1000,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Lutl"),
                }),
            },
            BlockItem {
                name: "luth",
                description: Some("GFXMMU LUT entry 0 high."),
                array: Some(Array::Regular(RegularArray { len: 1024, stride: 8 })),
                byte_offset: 0x1004,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Luth"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Bcr",
            extends: None,
            description: Some("GFXMMU buffer 0 configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pbo",
                    description: Some("Physical buffer offset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 19,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pbba",
                    description: Some("Physical buffer base address."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cr",
            extends: None,
            description: Some("GFXMMU configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "boie",
                    description: Some("Buffer 0 overflow interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 1 })),
                    enumm: None,
                },
                Field {
                    name: "ameie",
                    description: Some("AXI master error interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bs",
                    description: Some("Block size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ate",
                    description: Some("Address translation enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bpe",
                    description: Some("Buffer 0 packing enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 2 })),
                    enumm: None,
                },
                Field {
                    name: "bpm",
                    description: Some("Buffer 0 packing mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 2 })),
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dar",
            extends: None,
            description: Some("GFXMMU default alpha register."),
            bit_size: 32,
            fields: &[Field {
                name: "da",
                description: Some("Default alpha."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Dvr",
            extends: None,
            description: Some("GFXMMU default value register."),
            bit_size: 32,
            fields: &[Field {
                name: "dv",
                description: Some("Default value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fcr",
            extends: None,
            description: Some("GFXMMU flag clear register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "cbof",
                    description: Some("Clear buffer 0 overflow flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 1 })),
                    enumm: None,
                },
                Field {
                    name: "camef",
                    description: Some("Clear AXI master error flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Luth",
            extends: None,
            description: Some("GFXMMU LUT entry 0 high."),
            bit_size: 32,
            fields: &[Field {
                name: "lo",
                description: Some("Line offset."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 18,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lutl",
            extends: None,
            description: Some("GFXMMU LUT entry 0 low."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fvb",
                    description: Some("First valid block."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lvb",
                    description: Some("Last valid block."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Sr",
            extends: None,
            description: Some("GFXMMU status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bof",
                    description: Some("Buffer 0 overflow flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 1 })),
                    enumm: None,
                },
                Field {
                    name: "amef",
                    description: Some("AXI master error flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
