
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Mce",
        extends: None,
        description: Some("Memory cipher engine."),
        items: &[
            BlockItem {
                name: "cr",
                description: Some("MCE configuration register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cr"),
                }),
            },
            BlockItem {
                name: "sr",
                description: Some("MCE status register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Sr"),
                }),
            },
            BlockItem {
                name: "iasr",
                description: Some("MCE illegal access status register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Iasr"),
                }),
            },
            BlockItem {
                name: "iacr",
                description: Some("MCE illegal access clear register."),
                array: None,
                byte_offset: 0xc,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Iacr"),
                }),
            },
            BlockItem {
                name: "iaier",
                description: Some("MCE illegal access interrupt enable register."),
                array: None,
                byte_offset: 0x10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Iaier"),
                }),
            },
            BlockItem {
                name: "iaddr",
                description: Some("MCE illegal address register."),
                array: None,
                byte_offset: 0x24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Iaddr"),
                }),
            },
            BlockItem {
                name: "regcr",
                description: Some("MCE region 1 configuration register."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 16 })),
                byte_offset: 0x40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Regcr"),
                }),
            },
            BlockItem {
                name: "saddr",
                description: Some("MCE start address for region 1 register."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 16 })),
                byte_offset: 0x44,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Saddr"),
                }),
            },
            BlockItem {
                name: "eaddr",
                description: Some("MCE end address for region 1 register."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 16 })),
                byte_offset: 0x48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Eaddr"),
                }),
            },
            BlockItem {
                name: "mkeyr",
                description: Some(".MCE master key 0."),
                array: Some(Array::Regular(RegularArray { len: 8, stride: 4 })),
                byte_offset: 0x200,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Mkeyr"),
                }),
            },
            BlockItem {
                name: "fmkeyr",
                description: Some("MCE fast master key 0."),
                array: Some(Array::Regular(RegularArray { len: 8, stride: 4 })),
                byte_offset: 0x220,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fmkeyr"),
                }),
            },
            BlockItem {
                name: "cc1cfgr",
                description: Some("MCE cipher context 1 configuration register."),
                array: None,
                byte_offset: 0x240,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc1cfgr"),
                }),
            },
            BlockItem {
                name: "cc1nr",
                description: Some("MCE cipher context 1 nonce register 0."),
                array: Some(Array::Regular(RegularArray { len: 2, stride: 4 })),
                byte_offset: 0x244,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc1nr"),
                }),
            },
            BlockItem {
                name: "cc1keyr",
                description: Some("MCE cipher context 1 key register 0."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 4 })),
                byte_offset: 0x24c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc1keyr"),
                }),
            },
            BlockItem {
                name: "cc2cfgr",
                description: Some("MCE cipher context 2 configuration register."),
                array: None,
                byte_offset: 0x270,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc2cfgr"),
                }),
            },
            BlockItem {
                name: "cc2nr",
                description: Some("MCE cipher context 2 nonce register 0."),
                array: Some(Array::Regular(RegularArray { len: 2, stride: 4 })),
                byte_offset: 0x274,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc2nr"),
                }),
            },
            BlockItem {
                name: "cc2keyr",
                description: Some("MCE cipher context 2 key register 0."),
                array: Some(Array::Regular(RegularArray { len: 4, stride: 4 })),
                byte_offset: 0x27c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc2keyr"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cc1cfgr",
            extends: None,
            description: Some("MCE cipher context 1 configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ccen",
                    description: Some("Cipher context enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cclock",
                    description: Some("Cipher context lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keylock",
                    description: Some("Key lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mode",
                    description: Some("Authorized cipher mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keycrc",
                    description: Some("Key CRC."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "version",
                    description: Some("Version."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cc1keyr",
            extends: None,
            description: Some("MCE cipher context 1 key register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("cipher key, bits [31:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc1nr",
            extends: None,
            description: Some("MCE cipher context 1 nonce register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "scnonce",
                description: Some("Stream cipher nonce, bits [31:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc2cfgr",
            extends: None,
            description: Some("MCE cipher context 2 configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ccen",
                    description: Some("Cipher context enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cclock",
                    description: Some("Cipher context lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keylock",
                    description: Some("Key lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mode",
                    description: Some("Authorized cipher mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keycrc",
                    description: Some("Key CRC."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "version",
                    description: Some("Version."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cc2keyr",
            extends: None,
            description: Some("MCE cipher context 2 key register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("cipher key, bits [31:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc2nr",
            extends: None,
            description: Some("MCE cipher context 2 nonce register 0."),
            bit_size: 32,
            fields: &[Field {
                name: "scnonce",
                description: Some("Stream cipher nonce, bits [31:0]."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cr",
            extends: None,
            description: Some("MCE configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "glock",
                    description: Some("Global lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mklock",
                    description: Some("Master keys lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ciphersel",
                    description: Some("Cipher selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Eaddr",
            extends: None,
            description: Some("MCE end address for region 1 register."),
            bit_size: 32,
            fields: &[Field {
                name: "baddend",
                description: Some("Region address end."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fmkeyr",
            extends: None,
            description: Some("MCE fast master key 0."),
            bit_size: 32,
            fields: &[Field {
                name: "fmkey",
                description: Some("Fast master key bit 0 (i = 31 to 0)."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 32, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iacr",
            extends: None,
            description: Some("MCE illegal access clear register."),
            bit_size: 32,
            fields: &[Field {
                name: "iaef",
                description: Some("Illegal access error flag clear."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iaddr",
            extends: None,
            description: Some("MCE illegal address register."),
            bit_size: 32,
            fields: &[Field {
                name: "iadd",
                description: Some("Illegal address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iaier",
            extends: None,
            description: Some("MCE illegal access interrupt enable register."),
            bit_size: 32,
            fields: &[Field {
                name: "iaeie",
                description: Some("Illegal access error interrupt enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iasr",
            extends: None,
            description: Some("MCE illegal access status register."),
            bit_size: 32,
            fields: &[Field {
                name: "iaef",
                description: Some("Illegal access error flag."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Mkeyr",
            extends: None,
            description: Some(".MCE master key 0."),
            bit_size: 32,
            fields: &[Field {
                name: "mkey",
                description: Some("Master key bit 0 (i = 31 to 0)."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: Some(Array::Regular(RegularArray { len: 32, stride: 1 })),
                enumm: None,
            }],
        },
        FieldSet {
            name: "Regcr",
            extends: None,
            description: Some("MCE region 1 configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bren",
                    description: Some("Base region enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctxid",
                    description: Some("Context ID."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "enc",
                    description: Some("Encrypted region."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Saddr",
            extends: None,
            description: Some("MCE start address for region 1 register."),
            bit_size: 32,
            fields: &[Field {
                name: "baddstart",
                description: Some("Region address start."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Sr",
            extends: None,
            description: Some("MCE status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mkvalid",
                    description: Some("Master key valid."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fmkvalid",
                    description: Some("Fast master key valid."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "encdis",
                    description: Some("encryption disabled."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
