
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[
        Block {
            name: "Busif",
            extends: None,
            description: Some("ATON AXI bus interface unit."),
            items: &[
                BlockItem {
                    name: "ctrl",
                    description: Some("Bus interface control register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("BusifCtrl"),
                    }),
                },
                BlockItem {
                    name: "err",
                    description: Some("Bus interface error status register."),
                    array: None,
                    byte_offset: 0x10,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("BusifErr"),
                    }),
                },
            ],
        },
        Block {
            name: "Clkctrl",
            extends: None,
            description: Some("ATON internal clock controller."),
            items: &[
                BlockItem {
                    name: "ctrl",
                    description: Some("Clock controller control register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("ClkctrlCtrl"),
                    }),
                },
                BlockItem {
                    name: "agates0",
                    description: Some("Group-A infrastructure clock gates (lower 32)."),
                    array: None,
                    byte_offset: 0x8,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Agates"),
                    }),
                },
                BlockItem {
                    name: "agates1",
                    description: Some("Group-A infrastructure clock gates (upper 32)."),
                    array: None,
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Agates"),
                    }),
                },
                BlockItem {
                    name: "bgates",
                    description: Some("Group-B accelerator unit clock gates."),
                    array: None,
                    byte_offset: 0x10,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Bgates"),
                    }),
                },
            ],
        },
        Block {
            name: "Epochctrl",
            extends: None,
            description: Some("ATON Epoch Controller execution engine."),
            items: &[
                BlockItem {
                    name: "ctrl",
                    description: Some("Epoch controller control and status register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("EpochctrlCtrl"),
                    }),
                },
                BlockItem {
                    name: "addr",
                    description: Some("Blob start address register (8-byte aligned)."),
                    array: None,
                    byte_offset: 0x8,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("EpochctrlAddr"),
                    }),
                },
                BlockItem {
                    name: "irq",
                    description: Some("Epoch controller interrupt status/acknowledge register."),
                    array: None,
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("EpochctrlIrq"),
                    }),
                },
                BlockItem {
                    name: "label",
                    description: Some("Current/last executed blob section label (debug)."),
                    array: None,
                    byte_offset: 0x1c,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("EpochctrlLabel"),
                    }),
                },
                BlockItem {
                    name: "bc",
                    description: Some("Opcode/byte counter (debug)."),
                    array: None,
                    byte_offset: 0x20,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("EpochctrlBc"),
                    }),
                },
            ],
        },
        Block {
            name: "Intctrl",
            extends: None,
            description: Some("ATON interrupt controller."),
            items: &[
                BlockItem {
                    name: "ctrl",
                    description: Some("Interrupt controller control register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("IntctrlCtrl"),
                    }),
                },
                BlockItem {
                    name: "intreg",
                    description: Some("Latched interrupt status register."),
                    array: None,
                    byte_offset: 0x8,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Intstatus"),
                    }),
                },
                BlockItem {
                    name: "intset",
                    description: Some("Software interrupt set register."),
                    array: None,
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Intstatus"),
                    }),
                },
                BlockItem {
                    name: "intclr",
                    description: Some("Interrupt clear register (write 1 to clear)."),
                    array: None,
                    byte_offset: 0x10,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Intstatus"),
                    }),
                },
                BlockItem {
                    name: "intormsk",
                    description: Some("OR-mask registers for interrupt lines 0..3."),
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 4 })),
                    byte_offset: 0x14,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Intstatus"),
                    }),
                },
                BlockItem {
                    name: "intandmsk",
                    description: Some("AND-mask registers for interrupt lines 0..3."),
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 4 })),
                    byte_offset: 0x24,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Intstatus"),
                    }),
                },
            ],
        },
        Block {
            name: "Npu",
            extends: None,
            description: Some("ST Neural-ART accelerator (ATON) host interface."),
            items: &[
                BlockItem {
                    name: "clkctrl",
                    description: Some("Clock controller."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Clkctrl" }),
                },
                BlockItem {
                    name: "intctrl",
                    description: Some("Interrupt controller."),
                    array: None,
                    byte_offset: 0x1000,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Intctrl" }),
                },
                BlockItem {
                    name: "busif",
                    description: Some("Bus interface units."),
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 4096 })),
                    byte_offset: 0x2000,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Busif" }),
                },
                BlockItem {
                    name: "streng",
                    description: Some("Streaming engines."),
                    array: Some(Array::Regular(RegularArray { len: 10, stride: 4096 })),
                    byte_offset: 0x5000,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Streng" }),
                },
                BlockItem {
                    name: "epochctrl",
                    description: Some("Epoch controller."),
                    array: None,
                    byte_offset: 0x1e000,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Epochctrl" }),
                },
            ],
        },
        Block {
            name: "Streng",
            extends: None,
            description: Some("ATON streaming engine host interface."),
            items: &[BlockItem {
                name: "irq",
                description: Some("Streaming engine interrupt status/acknowledge register."),
                array: None,
                byte_offset: 0x3c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("StrengIrq"),
                }),
            }],
        },
    ],
    fieldsets: &[
        FieldSet {
            name: "Agates",
            extends: None,
            description: Some("Group-A clock gating register."),
            bit_size: 32,
            fields: &[Field {
                name: "gates",
                description: Some("Clock enable mask."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Bgates",
            extends: None,
            description: Some("Group-B unit clock gating register."),
            bit_size: 32,
            fields: &[Field {
                name: "gates",
                description: Some("Unit clock enable mask."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "BusifCtrl",
            extends: None,
            description: Some("Bus interface control register."),
            bit_size: 32,
            fields: &[Field {
                name: "en",
                description: Some("Bus interface enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "BusifErr",
            extends: None,
            description: Some("Bus interface error status register."),
            bit_size: 32,
            fields: &[Field {
                name: "err",
                description: Some("Bus error flags."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "ClkctrlCtrl",
            extends: None,
            description: Some("Clock controller control register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Clock controller enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clr",
                    description: Some("Clock controller synchronous clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "EpochctrlAddr",
            extends: None,
            description: Some("Blob base address register."),
            bit_size: 32,
            fields: &[Field {
                name: "addr",
                description: Some("32-bit physical address of blob start."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "EpochctrlBc",
            extends: None,
            description: Some("Byte/opcode counter register."),
            bit_size: 32,
            fields: &[Field {
                name: "count",
                description: Some("Executed instruction counter."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "EpochctrlCtrl",
            extends: None,
            description: Some("Epoch controller control register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Start epoch controller execution."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clr",
                    description: Some("Clear controller state."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sm",
                    description: Some("Single-step mode enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "confclr",
                    description: Some("Configuration clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "running",
                    description: Some("Controller execution status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "EpochctrlIrq",
            extends: None,
            description: Some("Epoch controller IRQ acknowledge register."),
            bit_size: 32,
            fields: &[Field {
                name: "irq",
                description: Some("IRQ flag (write back read value to ack)."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "EpochctrlLabel",
            extends: None,
            description: Some("Blob label debug register."),
            bit_size: 32,
            fields: &[Field {
                name: "label",
                description: Some("Current blob section label."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "IntctrlCtrl",
            extends: None,
            description: Some("Interrupt controller control register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Interrupt controller enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clr",
                    description: Some("Synchronous clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "confclr",
                    description: Some("Configuration clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Intstatus",
            extends: None,
            description: Some("Interrupt status and mask register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "streng_evt",
                    description: Some("Streaming engine completion events (engines 0..9)."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 10,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "streng_err",
                    description: Some("Streaming engine errors (engines 0..9)."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 10,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "busif_err",
                    description: Some("Bus interface error flags (BUSIF 0..1)."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ectrl_evt",
                    description: Some("Epoch controller end of epoch / IRQ event."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ectrl_noack",
                    description: Some("Epoch controller missing-acknowledge error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ectrl_err",
                    description: Some("Epoch controller execution error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "StrengIrq",
            extends: None,
            description: Some("Streaming engine IRQ status/acknowledge register."),
            bit_size: 32,
            fields: &[Field {
                name: "irq",
                description: Some("Interrupt pending flag (write 1 to acknowledge)."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[],
};
