
use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[
        Block {
            name: "Ch",
            extends: None,
            description: None,
            items: &[
                BlockItem {
                    name: "cr1",
                    description: Some("SAI configuration register 1."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Cr1"),
                    }),
                },
                BlockItem {
                    name: "cr2",
                    description: Some("SAI configuration register 2."),
                    array: None,
                    byte_offset: 0x4,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Cr2"),
                    }),
                },
                BlockItem {
                    name: "frcr",
                    description: Some("SAI frame configuration register."),
                    array: None,
                    byte_offset: 0x8,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Frcr"),
                    }),
                },
                BlockItem {
                    name: "slotr",
                    description: Some("SAI slot register."),
                    array: None,
                    byte_offset: 0xc,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Slotr"),
                    }),
                },
                BlockItem {
                    name: "im",
                    description: Some("SAI interrupt mask register."),
                    array: None,
                    byte_offset: 0x10,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Im"),
                    }),
                },
                BlockItem {
                    name: "sr",
                    description: Some("SAI status register."),
                    array: None,
                    byte_offset: 0x14,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Sr"),
                    }),
                },
                BlockItem {
                    name: "clrfr",
                    description: Some("SAI clear flag register."),
                    array: None,
                    byte_offset: 0x18,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Clrfr"),
                    }),
                },
                BlockItem {
                    name: "dr",
                    description: Some("SAI data register."),
                    array: None,
                    byte_offset: 0x1c,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Dr"),
                    }),
                },
            ],
        },
        Block {
            name: "Sai",
            extends: None,
            description: Some("Serial audio interface."),
            items: &[
                BlockItem {
                    name: "gcr",
                    description: Some("SAI global configuration register."),
                    array: None,
                    byte_offset: 0x0,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Gcr"),
                    }),
                },
                BlockItem {
                    name: "ch",
                    description: None,
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 32 })),
                    byte_offset: 0x4,
                    inner: BlockItemInner::Block(BlockItemBlock { block: "Ch" }),
                },
                BlockItem {
                    name: "pdmcr",
                    description: Some("SAI PDM control register."),
                    array: None,
                    byte_offset: 0x44,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Pdmcr"),
                    }),
                },
                BlockItem {
                    name: "pdmdly",
                    description: Some("SAI PDM delay register."),
                    array: None,
                    byte_offset: 0x48,
                    inner: BlockItemInner::Register(Register {
                        access: Access::ReadWrite,
                        bit_size: 32,
                        fieldset: Some("Pdmdly"),
                    }),
                },
            ],
        },
    ],
    fieldsets: &[
        FieldSet {
            name: "Clrfr",
            extends: None,
            description: Some("SAI clear flag register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "covrudr",
                    description: Some("Clear overrun / underrun."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cmutedet",
                    description: Some("Mute detection flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cwckcfg",
                    description: Some("Clear wrong clock configuration flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ccnrdy",
                    description: Some("Clear Codec not ready flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cafsdet",
                    description: Some("Clear anticipated frame synchronization detection flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clfsdet",
                    description: Some("Clear late frame synchronization detection flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cr1",
            extends: None,
            description: Some("SAI configuration register 1."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("SAIx audio block mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prtcfg",
                    description: Some("Protocol configuration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ds",
                    description: Some("Data size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lsbfirst",
                    description: Some("Least significant bit first."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ckstr",
                    description: Some("Clock strobing edge."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncen",
                    description: Some("Synchronization enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mono",
                    description: Some("Mono mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "outdriv",
                    description: Some("Output drive."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "saien",
                    description: Some("Audio block enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dmaen",
                    description: Some("DMA enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "nodiv",
                    description: Some("No divider."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mckdiv",
                    description: Some("Master clock divider."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "osr",
                    description: Some("Oversampling ratio for master clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mcken",
                    description: Some("Master clock generation enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cr2",
            extends: None,
            description: Some("SAI configuration register 2."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fth",
                    description: Some("FIFO threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fflush",
                    description: Some("FIFO flush."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tris",
                    description: Some("Tristate management on data line."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mute",
                    description: Some("Mute."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "muteval",
                    description: Some("Mute value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mutecnt",
                    description: Some("Mute counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cpl",
                    description: Some("Complement bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "comp",
                    description: Some("Companding mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dr",
            extends: None,
            description: Some("SAI data register."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Frcr",
            extends: None,
            description: Some("SAI frame configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "frl",
                    description: Some("Frame length."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsall",
                    description: Some("Frame synchronization active level length."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 7,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsdef",
                    description: Some("Frame synchronization definition."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fspol",
                    description: Some("Frame synchronization polarity."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsoff",
                    description: Some("Frame synchronization offset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Gcr",
            extends: None,
            description: Some("SAI global configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "syncin",
                    description: Some("Synchronization outputs."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncout",
                    description: Some("Synchronization outputs."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Im",
            extends: None,
            description: Some("SAI interrupt mask register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ovrudrie",
                    description: Some("Overrun/underrun interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mutedetie",
                    description: Some("Mute detection interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wckcfgie",
                    description: Some("Wrong clock configuration interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "freqie",
                    description: Some("FIFO request interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnrdyie",
                    description: Some("Codec not ready interrupt enable (AC'97)."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "afsdetie",
                    description: Some("Anticipated frame synchronization detection interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfsdetie",
                    description: Some("Late frame synchronization detection interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Pdmcr",
            extends: None,
            description: Some("SAI PDM control register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pdmen",
                    description: Some("PDM enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "micnbr",
                    description: Some("Number of microphones."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cken",
                    description: Some("Clock enable of bitstream clock number 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: Some(Array::Regular(RegularArray { len: 2, stride: 1 })),
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Pdmdly",
            extends: None,
            description: Some("SAI PDM delay register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dlyml",
                    description: Some("Delay line adjust for first microphone of pair 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                    enumm: None,
                },
                Field {
                    name: "dlymr",
                    description: Some("Delay line adjust for second microphone of pair 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 3,
                    array: Some(Array::Regular(RegularArray { len: 4, stride: 8 })),
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Slotr",
            extends: None,
            description: Some("SAI slot register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fboff",
                    description: Some("First bit offset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 5,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "slotsz",
                    description: Some("Slot size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "nbslot",
                    description: Some("Number of slots in an audio frame."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sloten",
                    description: Some("Slot enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Sr",
            extends: None,
            description: Some("SAI status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ovrudr",
                    description: Some("Overrun / underrun."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mutedet",
                    description: Some("Mute detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wckcfg",
                    description: Some("Wrong clock configuration flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "freq",
                    description: Some("FIFO request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnrdy",
                    description: Some("Codec not ready."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "afsdet",
                    description: Some("Anticipated frame synchronization detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfsdet",
                    description: Some("Late frame synchronization detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "flvl",
                    description: Some("FIFO level threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
